
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef DISPERSION_H
#define DISPERSION_H

#include "mxgui/image.h"

extern const mxgui::Image dispersion;

#endif //DISPERSION_H
